### ISSUE TITLE
MatchError in Page.current

### ISSUE THREAD

**Issue by ndarilek** [henrikerola/scaladin#19]
Getting the following partial exception when calling Page.current:

Caused by: scala.MatchError: com.vaadin.server.Page@57f4ea9d (of class com.vaadin.server.Page)
    at vaadin.scala.internal.WrapperUtil$.wrapperFor(WrapperUtil.scala:12)
    at vaadin.scala.Page$.current(Page.scala:20)
...

There's more, but the callstack isn't all that deep at Page.current.

**Comment by henrikerola** [comment]
Thanks for reporting
