### ISSUE TITLE
Scaladin for Scala 2.11 - NoClassDefFoundError GenTraversableOnce$class

### ISSUE THREAD

**Issue by kermitas** [henrikerola/scaladin#48]
Hi,
I was trying to run Scaladin 3.0.0 (Vaadin 7.1.13) on Scala 2.11 (Java 8). Those are exceptions that I get (hope that helps in moving Scaladin to Scala 2.11).

`lazy val sessionInitListeners: ListenersSet[ScaladinService.SessionInitEvent => Unit] = new ListenersTrait[ScaladinService.SessionInitEvent, SessionInitListener] {` causes:

```
java.lang.NoClassDefFoundError: scala/collection/GenTraversableOnce$class
    at vaadin.scala.server.ScaladinService$$anon$1.<init>(scaladinServices.scala:34) ~[scaladin-3.0.0.jar:3.0.0]
    at vaadin.scala.server.ScaladinService$class.sessionInitListeners(scaladinServices.scala:34) ~[scaladin-3.0.0.jar:3.0.0]
    at vaadin.scala.server.ScaladinServletService.sessionInitListeners$lzycompute(scaladinServices.scala:46) ~[scaladin-3.0.0.jar:3.0.0]
    at vaadin.scala.server.ScaladinServletService.sessionInitListeners(scaladinServices.scala:46) ~[scaladin-3.0.0.jar:3.0.0]
    at vaadin.scala.server.ScaladinServlet.registerUIProvider(ScaladinServlet.scala:16) ~[scaladin-3.0.0.jar:3.0.0]
    at vaadin.scala.server.ScaladinServlet.init(ScaladinServlet.scala:12) ~[scaladin-3.0.0.jar:3.0.0]
    at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:532) ~[jetty-all-server-8.1.14.v20131031.jar:8.1.14.v20131031]
    at org.eclipse.jetty.servlet.ServletHolder.getServlet(ServletHolder.java:415) ~[jetty-all-server-8.1.14.v20131031.jar:8.1.14.v20131031]
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:657) ~[jetty-all-server-8.1.14.v20131031.jar:8.1.14.v20131031]
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501) [jetty-all-server-8.1.14.v20131031.jar:8.1.14.v20131031]
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137) [jetty-all-server-8.1.14.v20131031.jar:8.1.14.v20131031]
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557) [jetty-all-server-8.1.14.v20131031.jar:8.1.14.v20131031]
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231) [jetty-all-server-8.1.14.v20131031.jar:8.1.14.v20131031]
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086) [jetty-all-server-8.1.14.v20131031.jar:8.1.14.v20131031]
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428) [jetty-all-server-8.1.14.v20131031.jar:8.1.14.v20131031]
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193) [jetty-all-server-8.1.14.v20131031.jar:8.1.14.v20131031]
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020) [jetty-all-server-8.1.14.v20131031.jar:8.1.14.v20131031]
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135) [jetty-all-server-8.1.14.v20131031.jar:8.1.14.v20131031]
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116) [jetty-all-server-8.1.14.v20131031.jar:8.1.14.v20131031]
    at org.eclipse.jetty.server.Server.handle(Server.java:366) [jetty-all-server-8.1.14.v20131031.jar:8.1.14.v20131031]
    at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494) [jetty-all-server-8.1.14.v20131031.jar:8.1.14.v20131031]
    at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:971) [jetty-all-server-8.1.14.v20131031.jar:8.1.14.v20131031]
    at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1033) [jetty-all-server-8.1.14.v20131031.jar:8.1.14.v20131031]
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644) [jetty-all-server-8.1.14.v20131031.jar:8.1.14.v20131031]
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235) [jetty-all-server-8.1.14.v20131031.jar:8.1.14.v20131031]
    at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82) [jetty-all-server-8.1.14.v20131031.jar:8.1.14.v20131031]
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:667) [jetty-all-server-8.1.14.v20131031.jar:8.1.14.v20131031]
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52) [jetty-all-server-8.1.14.v20131031.jar:8.1.14.v20131031]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_05]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_05]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_05]
Caused by: java.lang.ClassNotFoundException: scala.collection.GenTraversableOnce$class
    at java.net.URLClassLoader$1.run(URLClassLoader.java:372) ~[na:1.8.0_05]
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[na:1.8.0_05]
    at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_05]
    at java.net.URLClassLoader.findClass(URLClassLoader.java:360) ~[na:1.8.0_05]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_05]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_05]
    ... 31 common frames omitted
```

And then later exceptions:

```
javax.servlet.ServletException: com.vaadin.server.ServiceException: com.vaadin.server.ServiceException: No UIProvider has been added and there is no "UI" init parameter.
    at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:240) ~[vaadin-server-7.1.13.jar:7.1.13]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) ~[javax.servlet-3.0.0.v201112011016.jar:na]
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684) ~[jetty-all-server-8.1.14.v20131031.jar:8.1.14.v20131031]
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501) [jetty-all-server-8.1.14.v20131031.jar:8.1.14.v20131031]
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137) [jetty-all-server-8.1.14.v20131031.jar:8.1.14.v20131031]
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557) [jetty-all-server-8.1.14.v20131031.jar:8.1.14.v20131031]
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231) [jetty-all-server-8.1.14.v20131031.jar:8.1.14.v20131031]
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086) [jetty-all-server-8.1.14.v20131031.jar:8.1.14.v20131031]
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428) [jetty-all-server-8.1.14.v20131031.jar:8.1.14.v20131031]
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193) [jetty-all-server-8.1.14.v20131031.jar:8.1.14.v20131031]
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020) [jetty-all-server-8.1.14.v20131031.jar:8.1.14.v20131031]
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135) [jetty-all-server-8.1.14.v20131031.jar:8.1.14.v20131031]
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116) [jetty-all-server-8.1.14.v20131031.jar:8.1.14.v20131031]
    at org.eclipse.jetty.server.Server.handle(Server.java:366) [jetty-all-server-8.1.14.v20131031.jar:8.1.14.v20131031]
    at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494) [jetty-all-server-8.1.14.v20131031.jar:8.1.14.v20131031]
    at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:971) [jetty-all-server-8.1.14.v20131031.jar:8.1.14.v20131031]
    at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1033) [jetty-all-server-8.1.14.v20131031.jar:8.1.14.v20131031]
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644) [jetty-all-server-8.1.14.v20131031.jar:8.1.14.v20131031]
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235) [jetty-all-server-8.1.14.v20131031.jar:8.1.14.v20131031]
    at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82) [jetty-all-server-8.1.14.v20131031.jar:8.1.14.v20131031]
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:667) [jetty-all-server-8.1.14.v20131031.jar:8.1.14.v20131031]
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52) [jetty-all-server-8.1.14.v20131031.jar:8.1.14.v20131031]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_05]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_05]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_05]
Caused by: com.vaadin.server.ServiceException: com.vaadin.server.ServiceException: No UIProvider has been added and there is no "UI" init parameter.
    at com.vaadin.server.VaadinService.handleExceptionDuringRequest(VaadinService.java:1445) ~[vaadin-server-7.1.13.jar:7.1.13]
    at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1399) ~[vaadin-server-7.1.13.jar:7.1.13]
    at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:238) ~[vaadin-server-7.1.13.jar:7.1.13]
    ... 24 common frames omitted
Caused by: com.vaadin.server.ServiceException: No UIProvider has been added and there is no "UI" init parameter.
    at com.vaadin.server.ServletPortletHelper.checkUiProviders(ServletPortletHelper.java:179) ~[vaadin-server-7.1.13.jar:7.1.13]
    at com.vaadin.server.VaadinService.onVaadinSessionStarted(VaadinService.java:791) ~[vaadin-server-7.1.13.jar:7.1.13]
    at com.vaadin.server.VaadinService.createAndRegisterSession(VaadinService.java:745) ~[vaadin-server-7.1.13.jar:7.1.13]
    at com.vaadin.server.VaadinService.doFindOrCreateVaadinSession(VaadinService.java:701) ~[vaadin-server-7.1.13.jar:7.1.13]
    at com.vaadin.server.VaadinService.findOrCreateVaadinSession(VaadinService.java:642) ~[vaadin-server-7.1.13.jar:7.1.13]
    at com.vaadin.server.VaadinService.findVaadinSession(VaadinService.java:501) ~[vaadin-server-7.1.13.jar:7.1.13]
    at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1381) ~[vaadin-server-7.1.13.jar:7.1.13]
    ... 25 common frames omitted
```

I also recompiled Scaladin to use Scala 2.11.0 and tried to use it but in line 
`val root = new org.eclipse.jetty.webapp.WebAppContext`
I got

```
java.lang.SecurityException: class "javax.servlet.HttpConstraintElement"'s signer information does not match signer information of other classes in the same package
    at java.lang.ClassLoader.checkCerts(ClassLoader.java:895) ~[na:1.8.0_05]
    at java.lang.ClassLoader.preDefineClass(ClassLoader.java:665) ~[na:1.8.0_05]
    at java.lang.ClassLoader.defineClass(ClassLoader.java:758) ~[na:1.8.0_05]
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[na:1.8.0_05]
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:455) ~[na:1.8.0_05]
    at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[na:1.8.0_05]
    at java.net.URLClassLoader$1.run(URLClassLoader.java:367) ~[na:1.8.0_05]
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[na:1.8.0_05]
    at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_05]
    at java.net.URLClassLoader.findClass(URLClassLoader.java:360) ~[na:1.8.0_05]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_05]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_05]
```

**Comment by henrikerola** [comment]
3.1trunk builds now with both Scala 2.10 and 2.11. It's compatible with Vaadin 7.2
