### ISSUE TITLE
Unable to convert value of type scala.math.BigDecimal to presentation type class java.lang.String

### ISSUE THREAD

**Issue by thehappycoder** [henrikerola/scaladin#57]
This happens starting from vaadin-7.2.0

Caused by: com.vaadin.data.util.converter.Converter$ConversionException: Unable to convert value of type scala.math.BigDecimal to presentation type class java.lang.String. No converter is set and the types are not compatible.
    at com.vaadin.data.util.converter.ConverterUtil.convertFromModel(ConverterUtil.java:116)
    at com.vaadin.ui.AbstractField.convertFromModel(AbstractField.java:708)
    at com.vaadin.ui.AbstractField.convertFromModel(AbstractField.java:693)
    at com.vaadin.ui.AbstractField.setPropertyDataSource(AbstractField.java:629)

**Comment by thehappycoder** [comment]
I'd love to build my app with scaladin but I think I give up. Numerous problems make me switch to something that is supported in scala world.
